export const FETCH__USERS = 'RECIEVE__USERS';
export const FETCH__START__USERS = 'FETCH__START__USERS';
export const FETCH__ERROR__USERS = 'FETCH__ERROR__USERS';

export const FETCH__START__COMMENTS = 'FETCH__START__COMMENTS';
export const FETCH__ERROR__COMMENTS = 'FETCH__ERROR__COMMENTS';
export const FETCH__COMMENTS = 'RECIEVE__COMMENTS';

export const UPDATE__USER = 'UPDATE__USER';
